# Generated by Django 5.2.2 on 2025-06-08 07:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('feedback_type', models.CharField(choices=[('rider_to_driver', 'Rider to Driver'), ('driver_to_rider', 'Driver to Rider')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='rides.ride')),
            ],
            options={
                'unique_together': {('ride', 'feedback_type')},
            },
        ),
    ]
