# Generated by Django 5.2.2 on 2025-06-08 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cab_types')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_year', models.PositiveIntegerField()),
                ('vehicle_photo', models.ImageField(blank=True, null=True, upload_to='vehicle_pics')),
                ('license_photo', models.ImageField(blank=True, null=True, upload_to='license_pics')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('availability_status', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('on_trip', 'On Trip')], default='offline', max_length=20)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('total_rides', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cab_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='drivers.cabtype')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='users.userprofile')),
            ],
        ),
    ]
